### ISSUE TITLE
how to use 

### ISSUE THREAD

**Issue by ghost** [crops/extsdk-container#5]
I've build my image (poky) within "crops/poky-container" I wanna use SDK from there instead of "--url http://someserver/extensible_sdk_installer.sh", how to set it up?

`
docker run --rm -it -v /home/ubuntu/work/yoctosdk/:/workdir crops/extsdk-container --url file:///home/ubuntu/work/yocto/poky/build/tmp/deploy/sdk/poky-glibc-x86_64-core-image-minimal-i586-toolchain-2.4.1.sh
`

getting this

    Attempting to download file:///home/ubuntu/work/yocto/poky/build/tmp/deploy/sdk/poky-glibc-x86_64-core-image-minimal-i586-toolchain-2.4.1.sh
    curl: (37) Couldn't open file /home/ubuntu/work/yocto/poky/build/tmp/deploy/sdk/poky-glibc-x86_64-core-image-minimal-i586-toolchain-2.4.1.sh
    Unable to download "file:///home/ubuntu/work/yocto/poky/build/tmp/deploy/sdk/poky-glibc-x86_64-core-image-minimal-i586-toolchain-2.4.1.sh".

**Comment by bavery22** [comment]
Basically, you need to build the sdk now that you have the image. (bitbake
< your *image >* -c populate_sdk)
see:
https://www.yoctoproject.org/docs/latest/mega-manual/mega-manual.html#sdk-building-an-sdk-installer

Then you can install that image in the poky container if you want by
following the "Run the Installer " section. Remember the poky container is
ephemeral so if you exit it you will lose your setup.

the extsdk container can install the sdk you build by following a --url
file:/path/to/my/sdk/installscript so that might be a better choice as it
will install it outside the container so it is available on container
restart.

g'luck!

**Comment by ghost** [comment]
by installing SDK into extsdk container how can it be set-up environment variables by sourcing environment*   script? I wanna use SDK/cross compiler to develop applications. 

```
ubuntu@ubuntu:~/work/yoctosdk$ source environment-setup-corei7-64-poky-linux 
bash: /sdk/buildtools/environment-setup*: No such file or directory
SDK environment now set up; additionally you may now run devtool to perform development tasks.
Run devtool --help for further details.

```
